name: yiul
version: 1.0

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -j4
- +RTS -A32M -RTS

dependencies:
- aeson
- array
- base
- bytestring
- Cabal
- containers
- dir-traverse
- directory
- filepath
- generic-lens
- ghc
- ghc-paths
- lens
- mtl
- optparse-applicative
- pretty-simple
- text
- topograph
- unordered-containers

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - yiul
  ghc-options:
  - -threaded
  - -rtsopts
  - '"-with-rtsopts=-N -T"'
