name: yiul
version: 1.0

ghc-options:
- -Wall

dependencies:
- array
- base
- bytestring
- containers
- dir-traverse
- directory
- filepath
- generic-lens
- ghc
- ghc-paths
- lens
- mtl
- pretty-simple
- text

executable:
  main: Main.hs
